services:

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./logs:/app/logs
    depends_on:
      - redis

  worker:
    build: ./worker
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./logs:/app/logs
    depends_on:
      - redis

  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
