services:

  backend:
    build: ./backend

    container_name: backend

    ports:
      - "8000:8000"

    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed

    depends_on:
      - redis

  redis:
    image: redis:latest

    container_name: redis

    ports:
      - "6379:6379"

  worker1:
    build: ./backend

    container_name: worker1

    command: python worker.py

    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed

    depends_on:
      - redis

  worker2:
    build: ./backend

    container_name: worker2

    command: python worker.py

    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed

    depends_on:
      - redis

  worker3:
    build: ./backend

    container_name: worker3

    command: python worker.py

    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed

    depends_on:
      - redis
